package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"spectre/services"
)

// GetIntradayRead returns the most recent advisory LLM market-read (cached).
// The read is generated by the cron every ~10 min during market hours.
func GetIntradayRead(c *gin.Context) {
	read := services.GetLatestIntradayRead()
	if read == nil {
		c.JSON(http.StatusOK, gin.H{
			"available": false,
			"message":   "No read yet — generated every 10 min during market hours. Use Refresh to generate one now.",
		})
		return
	}
	c.JSON(http.StatusOK, gin.H{"available": true, "data": read})
}

// RefreshIntradayRead generates a fresh advisory read on demand (button in the UI).
func RefreshIntradayRead(c *gin.Context) {
	signal, err := services.GenerateTradeSignal()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	oi, _ := services.FetchOIChain()
	read, err := services.FetchIntradayRead(signal, oi)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"available": true, "data": read})
}
